[package]
name = "mcstat"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.45", features = ["derive"] }
colored = "3.0.0"
image = "0.25.6"
mcping = "0.2.0"
termimage = "1.2.2"
uuid = "1.18.0"

[patch.crates-io]
mcping = { path = "./patch/mcping" }
